name: EAS Build
on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

#Cancel other running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 📦 Setup Project
        uses: ./.github/actions/setup-node-yarn-eas-install
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: eas build -p android all --non-interactive --no-wait
